version: '3'
services:
  elasticsearch:  
    image: docker.elastic.co/elasticsearch/elasticsearch:7.7.0
    container_name: elasticsearch1
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - http.cors.enabled=true
      - http.cors.allow-origin=*
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
      - "discovery.type=single-node"
    networks:
      - elastic

  kibana:
    image: docker.elastic.co/kibana/kibana:7.7.0
    container_name: kibana1
    ports:
      - "5601:5601"
    networks:
      - elastic
    depends_on:
      - elasticsearch
    links:
      - elasticsearch

  grafana:
    image: grafana/grafana
    container_name: grafana1
    ports:
      - "3000:3000"
    networks:
      - elastic
    depends_on:
      - elasticsearch
    links:
      - elasticsearch
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181"
    hostname: zookeeper
    networks:
      - elastic  
    depends_on:
      - elasticsearch    
  kafka:
    image: wurstmeister/kafka #confluentinc/cp-kafka:latest
    container_name: kafka1
    command: [start-kafka.sh]
    ports:
      - "9092:9092"
    hostname: kafka
    environment:
      KAFKA_CREATE_TOPICS: "UploadFile:1:1,GetFile:1:1,TrackUpload:1:1,GetEmailContent:1:1" # topic:partition:replicas
      KAFKA_ADVERTISED_HOST_NAME: kafka # docker-machine ip
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - elastic
    depends_on:
      - zookeeper
    links:
      - elasticsearch

  #filebeat:
  #  image: docker.elastic.co/beats/filebeat:6.4.3
  #  container_name: filebeat1
  #  command: filebeat -e -strict.perms=false
  #  volumes:
  #    - ./filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
  #    - ./filebeat/filebeat.template.json:/usr/share/filebeat/filebeat.template.json:ro
  #    - /opt/log-app/filebeat-logs:/var/log/filebeat
  #    - /opt/log-app/filebeat:/opt/log-app/filebeat
  #    - /var/lib/docker/containers:/var/lib/docker/containers:ro
  #    - /var/run/docker.sock:/var/run/docker.sock
  #  environment:
  #    - strict.perms=false
  #    - setup.kibana.host=kibana1:5601
  #    - output.elasticsearch.hosts=["elasticsearch1:9200"]
  #  depends_on:
  #    - elasticsearch
  #  networks:
  #    - elastic
  #  links:
  #     - elasticsearch
  #     - kibana

networks:
  elastic:
    driver: bridge